### ISSUE TITLE
ImportError: cannot import name 'smart_unicode'

### ISSUE THREAD

**Issue by Flimm** [hzdg/django-staticbuilder#11]
When I run `python manage.py collectforbuild`, I get this error:

```
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/example/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/example/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/example/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/example/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/example/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/example/env/src/django-staticbuilder/staticbuilder/management/commands/collectforbuild.py", line 7, in <module>
    from django.utils.encoding import smart_unicode
ImportError: cannot import name 'smart_unicode'
```

If I look up the documentation for [`smart_unicode`](https://docs.djangoproject.com/en/1.10/ref/utils/#django.utils.encoding.smart_unicode), it seems that this function is only available in Python 2. I'm running Python 3.5.

**Comment by Huini8226** [comment]
and can you solve the problem now ?

**Comment by Flimm** [comment]
My pull request #12 was merged, and the new version is on PyPI, so this is fixed now.
